PREFIX kap_param: <https://data.rivm.nl/data/nvip/bigfood/kap/parameter#>
PREFIX : <http://purl.obolibrary.org/obo/foodon.owl#>
PREFIX ncbi: <https://www.ncbi.nlm.nih.gov/>
PREFIX ro: <http://purl.obolibrary.org/obo/RO>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX nevo: <http://www.foodvoc.org/resource/nevo#>
PREFIX fobi: <http://purl.obolibrary.org/obo/FOBI>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX leda: <http://example.org/temporary_identifier/LEDA#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX fio: <http://www.foodvoc.org/resource/fio#>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX saref: <https://saref.etsi.org/core/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX foodon: <http://purl.obolibrary.org/obo/FOODON>

# Add derives from for complete view. 
SELECT distinct ?ncbilabel ?class ?classlabel ?queryclasslabel ?datasetlabel ?dataavailable
WHERE {
  {?restriction rdf:type owl:Restriction ;
               owl:onProperty ro:_0001000 ; #in taxon
               owl:someValuesFrom ncbitaxon:4232 . #sunflower 
  	ncbitaxon:4232 rdfs:label ?ncbilabel . 
    ?class  rdfs:subClassOf ?restriction .  
  	?class rdfs:label ?classlabel . 
    ?queryclass rdfs:subClassOf* ?class . 
    ?queryclass rdfs:label ?queryclasslabel .
    }
  	UNION
    {?restriction rdf:type owl:Restriction ;
               owl:onProperty ro:_0001000 ; #in taxon
               owl:someValuesFrom ncbitaxon:4232 . #sunflower 
  	ncbitaxon:4232 rdfs:label ?ncbilabel . 
    ?class  rdfs:subClassOf ?restriction .  
    ?class rdfs:label ?classlabel .     
  	?queryclass rdfs:subClassOf* ?class . 
  	?queryclass rdfs:label ?queryclasslabel .
	?variable rdf:type fio:FoodItem . 
  	?variable rdf:type ?queryclass . 
    ?variable fio:hasImpact ?impact . 
    ?variable rdfs:label ?datasetlabel . 
        filter(lang(?datasetlabel) = "en")
    BIND("LCA data available" as ?dataavailable)        
}
  UNION
  {?restriction rdf:type owl:Restriction ;
               owl:onProperty ro:_0001000 ; #in taxon
               owl:someValuesFrom ncbitaxon:4232 . #sunflower 
  	ncbitaxon:4232 rdfs:label ?ncbilabel . 
    ?class  rdfs:subClassOf ?restriction .  
    ?class rdfs:label ?classlabel .     
  	?queryclass rdfs:subClassOf* ?class . 
  	?queryclass rdfs:label ?queryclasslabel .
	?variable rdf:type fio:FoodItem . 
  	?variable rdf:type ?queryclass . 
    ?variable skos:prefLabel ?datasetlabel .   
        filter(lang(?datasetlabel) = "en")
    ?variable fio:hasNutritionalValue ?nutrient . 
         BIND("Nutrient data available" as ?dataavailable)
  }
    UNION
    {
     ?restriction rdf:type owl:Restriction ;
               owl:onProperty ro:_0001000 ; #in taxon
               owl:someValuesFrom ncbitaxon:4232 . #sunflower 
  	ncbitaxon:4232 rdfs:label ?ncbilabel . 
    ?class  rdfs:subClassOf ?restriction .  
    ?class rdfs:label ?classlabel .     
  	?queryclass rdfs:subClassOf* ?class . 
  	?queryclass rdfs:label ?queryclasslabel .
	?variable rdf:type sosa:FeatureOfInterest . 
  	?variable rdf:type ?queryclass . 
    ?variable kap_param:hasKapName ?datasetlabel . 
     filter(lang(?datasetlabel) = "en")
     BIND("Chemical foodsafety data available" as ?dataavailable)
    } 
} order by desc(?datasetlabel)
  