# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.4
  hooks:
  - id: autopep8
- repo: https://github.com/pycqa/flake8.git
  rev: 6.1.0
  hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
    #   max-line-length: 100
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.4
    hooks:
    -   id: nbqa-isort
        files: \.ipynb
