PREFIX nevo: <http://www.foodvoc.org/resource/nevo#>
PREFIX fobi: <http://purl.obolibrary.org/obo/FOBI>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX leda: <http://example.org/temporary_identifier/LEDA#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX fio: <http://www.foodvoc.org/resource/fio#>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX foodon: <http://purl.obolibrary.org/obo/FOODON>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT distinct ?grouplabel ?foodname ?food_item ?impactlabel ?value ?impactunit
WHERE {
     {
        ?foodontype rdfs:subClassOf* foodon:_00001264 .
        BIND("Legume food product" AS ?grouplabel)
    }
    UNION
    {
        ?foodontype rdfs:subClassOf* foodon:_00001248 .
        BIND("Fish food product" AS ?grouplabel)
    }
    UNION
    {
        ?foodontype rdfs:subClassOf* foodon:_00001006 .
        BIND("Mamallian meat food product" AS ?grouplabel)
    }
    UNION
    {
        ?foodontype rdfs:subClassOf* foodon:_00001057.
        BIND("Plant fruit food product" AS ?grouplabel)
    }

    ?food_item rdf:type fio:FoodItem . 
    ?food_item rdf:type ?foodontype . 
    ?food_item rdfs:label ?foodname . 
    ?food_item fio:hasImpact ?impact . 
    FILTER(LANG(?foodname) = "en") 
    ?impact om:hasValue ?impactvalue . 
    ?impact rdfs:label "Global warming"@en . 
    ?impact rdfs:label ?impactlabel . 
    ?impactvalue om:hasNumericalValue ?value . 
    ?impactvalue om:hasUnit ?impactunit . 
    FILTER(isLiteral(?impactunit))
} ORDER BY DESC(?value)