PREFIX ncbi: <https://www.ncbi.nlm.nih.gov/>
PREFIX ro: <http://purl.obolibrary.org/obo/RO>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX nevo: <http://www.foodvoc.org/resource/nevo#>
PREFIX fobi: <http://purl.obolibrary.org/obo/FOBI>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX fio: <http://www.foodvoc.org/resource/fio#>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX saref: <https://saref.etsi.org/core/>
PREFIX kap: <http://example.org/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX foodon: <http://purl.obolibrary.org/obo/FOODON>


# Add derives from for complete view. 
SELECT ?ncbilabel ?classlabel ?queryclasslabel ?ingredientlabel ?restriction_ex ?any_taxon 
WHERE { {
    ?fooditem rdf:type ?queryclass . 
    ?fooditem rdf:type fio:FoodItem . 
    ?fooditem fobi:_00425 ?anyproduct .     
    ?fooditem rdfs:label ?ingredientlabel . 
        FILTER(lang(?ingredientlabel) = "en")    
    ?queryclass rdfs:subClassOf* ?class . 
   	?queryclass rdfs:label ?queryclasslabel .
  	?restriction1 rdf:type owl:Restriction ;
               owl:onProperty ro:_0001000 ; #in taxon
               owl:someValuesFrom ?any_taxon .
  	?any_taxon rdfs:label ?ncbilabel . 
    ?any_taxon rdfs:subClassOf* obo:NCBITaxon_33090 .  # from green plants
    ?class  rdfs:subClassOf ?restriction1 .  
  	?class rdfs:label ?classlabel . 
#    BIND("in taxon relation" as ?restriction_ex)
    } UNION {    
    ?fooditem rdf:type ?queryclass . 
    ?fooditem rdf:type fio:FoodItem . 
    ?fooditem fobi:_00425 ?anyproduct .     
    ?fooditem rdfs:label ?ingredientlabel . 
    FILTER(lang(?ingredientlabel) = "en")
    ?queryclass rdfs:subClassOf* ?class . 
   	?queryclass rdfs:label ?queryclasslabel .
  	?restriction2 rdf:type owl:Restriction ;
               owl:onProperty ro:_0002162 ; #derives from
               owl:someValuesFrom ?any_taxon .
  	?any_taxon rdfs:label ?ncbilabel . 
    ?any_taxon rdfs:subClassOf* obo:NCBITaxon_33090 .  # from green plants
#    BIND("derives from" as ?restriction_ex)
    ?class  rdfs:subClassOf ?restriction2 .  
  	?class rdfs:label ?classlabel . }
} 
    
    